steps:
  - name: node:13
    entrypoint: npm
    args: ['install']

  - name: node:13
    entrypoint: npm
    args: ['run', 'build:ssr']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'
